version: '2.0'

services:
  cerythme:
    container_name: frontend
    build:    
      context: .
      dockerfile: ./Dockerfile
      # args:
      #   - VITE_BACKEND_URL = https://graytiger-backend-mwjszocsqa-ew.a.run.app
    environment:
      # - "VITE_BACKEND_URL=$VITE_BACKEND_URL"
      - "VITE_BACKEND_URL=https://graytiger-backend-mwjszocsqa-ew.a.run.app"
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./frontend:/app