version: '3.1'
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: gunicorn ./backend/main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:22 --timeout 600
    ports:
      - "8000:22"
    expose:
      - "8000"
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    command: nginx -g daemon off;
    ports:
      - "8001:80"
    expose:
      - "8001"
    env_file:
      - ./frontend/.env
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'BD-DeTest'
    ports:
      - "3306:3306"
    expose:
      - "3306"