version: '3.1'
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:22 --timeout 600
    ports:
      - "8000:22"
    expose:
      - "8000"
    env_file:
      - .env
  #frontend:
  #  build:
  #    context: .
  #    dockerfile: frontend.Dockerfile
  #  command: nginx -g 'daemon off;'
  #  ports:
  #    - "8001:80"
  #  expose:
  #    - "8001"
  # The credentials are visibles because this database is just a test and it will be removed
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"