version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports:
      - 3000:8080

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.yml
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    # depends_on:
    #   - db

  reverse_proxy:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      # - db
      - backend
      - frontend

  # db:
  #   image: mysql
  #   container_name: db
  #   restart: always
  #   volumes:
  #     - type: volume
  #       source: ecom_db_backup
  #       target: /var/lib/mysql
  #   env_file: ./db/.env
  #   ports:
  #     - 3307:3306

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

# volumes:
#   ecom_db_backup:
#     external: true
