version: "3.8"

services:
  db:
    image: mysql:8.0
    volumes:
      - vinyls:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'vinyls'
      MYSQL_USER: 'customer'
      MYSQL_PASSWORD: 'iwantvinyls'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - backend
    ports:
      - 3306:3306
    expose:
      - 3306

  api:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 8888:80

volumes:
  vinyls:

networks:
  backend: