version: '3.8'

services:
  mysqldb:
    image: mysql:5.7 
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=e_com
    ports:
      - 3307:3006
    volumes:
      - db:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql


      
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=admin
      - DB_PASSWORD=root
      - DB_NAME=e_com
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db: