version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$DB_PORT
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql


      
  app:
    depends_on:
      - mysqldb
    build: .
    container_name: backend_app
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

volumes: 
  db: