name: backend-ci
run-name: backend continuous integration workflow
on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: Install dependencies
        run: npm install
        working-directory: ./backend
      - 
        name: Create Environment variables file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: ./backend
          file_name: .env
          PORT: ${{ secrets.PORT}}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MYSQLDB_LOCAL_PORT: ${{ secrets.MYSQLDB_LOCAL_PORT }}
          NODE_LOCAL_PORT: ${{ secrets.NODE_LOCAL_PORT }}
          fail_on_empty: false
      #- 
        #name: Execute tests
        #run: npm test
        #working-directory: ./backend
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: v0.6.3
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build docker images
        run: docker-compose -f ./backend/docker-compose.yml build
      - 
        name: Test docker images
        run: docker-compose -f ./backend/docker-compose.yml up -d
      - 
        name: Check Container
        run: docker ps 
      -
        name: Publish to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: moaguirar/e-com:api-latest,moaguirar/e-com:dev-api
      
