name: Black

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.9"
          cache: "pip" # caching pip dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
  
  black:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Run Black
        uses: psf/black@stable
        with:
          option: "--check --verbose"
          version: "22.10.0"
          src: "./backend"

  isort:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - name: isort
        uses: isort/isort-action@v1.1.0
        with:
            requirements: "requirements.txt"
    
  mypy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - name: Run mypy
        run : |
          mypy ./backend --config-file ./backend/mypy.ini

  pytest:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - name: Run pytest
        run : |
          pytest
        
  deploy:
    needs: [black, isort, mypy, pytest]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: backend:latest