name: backend-ci
run-name: backend continuous integration workflow
on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      -
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: Install dependencies
        run: npm install
        working-directory: ./backend
      - 
        name: Create Environment variables file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: ./backend
          file_name: .env
          PORT: ${{ secrets.PORT}}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MYSQLDB_LOCAL_PORT: ${{ secrets.MYSQLDB_LOCAL_PORT }}
          NODE_LOCAL_PORT: ${{ secrets.NODE_LOCAL_PORT }}
          fail_on_empty: true
      #- 
        #name: Execute tests
        #run: npm test
        #working-directory: ./backend
      - 
        name: Check credentials
        run: echo  ${{ secrets.DOCKERHUB_USERNAME }} | sed 's/./& /g'
      - 
        name: Check secrets
        run: echo  ${{ secrets.DOCKERHUB_DOCKER_REGISTRY }} | sed 's/./& /g'
      -
        name: Login to registry
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${{ secrets.DOCKER_REGISTRY}}
        
     

      

        
     
      
