name: backend-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install poetry
      - run: poetry install 
      - run: poetry run pytest tests/