name: backend-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_call:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install poetry
      - run: poetry install 
      - run: poetry run pytest tests/
  build:
    needs: test-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Building docker images and push to the registry
        run: |
          docker login -u _json_key_base64 -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}  https://europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/greenfish
          docker build -t backend -f Dockerfile .
          docker tag backend  europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/greenfish/backend:0.0.1
