name: CI
run-name: integration workflow
on:
  push:
    branches:
      - dev
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build docker images
        run: docker-compose -f ./backend/docker-compose.yml build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Test docker images
        run: docker-compose -f ./backend/docker-compose.yml up -d


