name: Deploy
on: 
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: 'IT1PAwylPkYkGg.atlasv1.Ws2fkPdeHCTgNytxUzjt88NEXwt6njKbg4JKYX6t7jGFXINZCsT43ZwClS9hRM5xjto'
      - run: terraform init
      - run: terraform apply -auto-approve -input=False 