name: Deployment 
run-name: Continuous Integration Continuous Deployment workflow 
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  api-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: Install dependencies
        run: npm install
        working-directory: ./backend
      #- 
        #name: Run tests
        #run: npm test
        #working-directory: ./backend
      -
        name: Build docker image
        working-directory: ./backend
        run: docker build -t backend-app .

      # Push step to be added 

  webapp-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - 
        name: Install angular/cli
        run: npm install -g @angular/cli
        working-directory: ./frontend
      - 
        name: Build
        run: npm run build
        working-directory: ./frontend
      #- 
        #name: Run tests
        #run: npm test
        #working-directory: ./frontend
      - 
        name: Build docker image
        working-directory: ./frontend
        run: docker build -t frontend-app .

      # Push step to be added     
      
  delivery:
    needs: [api-build,webapp-build]
    name: Countinuous delivery
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      -
        name: Get latest tag
        run: git tag
      #-
        #name: Create release branche
        #run: git checkout -b release/v0.1.0
      #- 
        #name: Push release branch
        #run: git push origin release/v0.1.0
  deployment:
    needs : delivery
    name: Countinuous deployment
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -  
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.API_TF_TOKEN }}
      -
        name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - 
        name: Terraform Init
        id: init
        run: terraform init
      -
        name: Terraform Validate
        id: validate
        run: terraform validate -no-color
     