name: Deployment 
run-name: Continuous Integration Continuous Deployment workflow 
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  delivery:
    name: Countinuous delivery
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      -
        name: Create release branche
        run: git checkout -b release/v0.1.0
      - 
        name: Push release branch
        run: git push origin release/v0.1.0
      


  