name: Docker - Frontend

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login and push
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/frontend:latestd ./frontend
          docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
