# This is a basic workflow to help you get started with Actions

name: DockerDeploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'
      - 'back_docker'
  pull_request:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/bluelion
          username: _json_key_base64
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Back docker image
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ../../backend
          # Note: tags has to be all lower-case
          tags: europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/bluelion
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}    

      - name: Back-end digest
        run: echo ${{ steps.docker_build.outputs.digest }}