name: Frontend
on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
      - name: Build and push 
        run: | 
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/frontend:1.0.8 ./frontend
          docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:1.0.8
