name: frontend-ci
run-name: frontend integration workflow
on:
  push:
    branches:
      - dev
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - 
        name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - 
        name: Install angular/cli
        run: npm install -g @angular/cli
        working-directory: ./frontend
      - 
        name: Build
        run: npm run build
        working-directory: ./frontend
      #- 
        #name: Run tests
        #run: npm test
        #working-directory: ./frontend
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: v0.6.3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build docker image
        working-directory: ./frontend
        run: docker build -t frontend-app .
      - 
        name: Test docker image
        run: docker run --name frontend -d -p 8080:80 frontend-app
      - 
        name: Check Container
        run: docker ps 
      -
        name: Publish to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: moaguirar/e-com:dev-frontend
    
