name: Front-end

on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AngualrProject
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build:prod
      
    #- name: Test
      #run: npm run test
      
    #- name: Lint
      #run: npm run lint
      
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.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 }}
        publish_dir: dist/ecommerce
        enable_jekyll: true
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/redpanda/frontend:1.3.2
      - name: Login to registry
        run : docker login -u _json_key_base64 -p ${{ secrets.DOCKER_PWD }} https://europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/redpanda
      - name: push image 
        run: docker push europe-west1-docker.pkg.dev/ceri-m1-ecommerce-2022/redpanda/frontend:1.3.2
