
name: deploy-actions
run-name: ${{ github.actor }} terraform deploy 
on: [push]
jobs:
  call-front-action:
    uses: ./.github/workflows/front-action.yml
  call-back-action:
    uses: ./.github/workflows/back-action.yml
  call-deploy-action:
    uses: ./.github/workflows/deploy-action.yml