name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AngualrProject
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build:prod
      
    - name: Test
      run: npm run test
      
    - name: Lint
      run: npm run lint
      
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.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 }}
        publish_dir: dist/ecommerce
        enable_jekyll: true
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/src

    # Checks out the entire repo.
    steps:
    - name: Checks out repo
      uses: actions/checkout@v1

    # Generates a openapi.yaml file based on the FastAPI project.
    - name: Generate OpenAPI file
      uses: column-street/fastapi-openapi-specs-action@v1.0.0
      with:
        fileName: songs.py
        appName: app
      
    # Pushes all of these changes into the GitHub repository.
    #- name: Push changes to backend branch
     # uses: ad-m/github-push-action@master
      #with:
       # github_token: ${{ secrets.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 }}
        #branch: main
        #force: True
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d
