name: mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.9"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          if [ -f ./backend/requirements.txt ]; then pip install -r ./backend/requirements.txt; fi
      - name: Run mypy
        run : |
          mypy ./backend --config-file ./backend/mypy.ini