name: Deploy

on:
  push:
    branches:
      - "main"
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TOKEN_TF }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: terraform plan -no-color -input=false
        
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=False 
