name: CI-workflow
run-name: integration workflow
on:
  push:
    branches:
      - dev
      - sre
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build docker images
        run: docker-compose up -d
        

